#!/usr/bin/env python3
"""Week 3 — real-content comparison harness: MediaPipe AutoFlip vs ClipAI.

For every clip in ``tests/real_content/manifest.json``:

  1. Load the cached AutoFlip JSON timeline from
     ``tests/autoflip_reference_outputs/<slug>.json`` (generated by
     ``reference/autoflip/run_one.sh`` on the one-time Docker build).
  2. Build a ClipAI timeline in the same JSON shape — via the
     ``export_autoflip_compatible`` translator over a cached
     extraction (see below), or skipped with a note when the
     pipeline can't be invoked in the current environment.
  3. Optionally load a human ground-truth sidecar from
     ``tests/real_content/ground_truth/<slug>.json``.
  4. Score every available timeline with
     ``autoflip_parity_metrics.cut_to_hold_ratio`` plus the acceleration
     / jerk / overlap metrics.
  5. Emit a per-content-type markdown rollup to
     ``docs/week3_real_content_results.md`` and a raw JSON dump to
     ``/tmp/week3_results.json`` (or wherever ``--json-out`` points).

Usage:

    python -m backend.scripts.compare_autoflip_vs_clipai \\
        --manifest tests/real_content/manifest.json \\
        --autoflip-outputs tests/autoflip_reference_outputs/ \\
        --output docs/week3_real_content_results.md \\
        --json-out /tmp/week3_results.json

Optional flags:

    --filter "panel_*"         Only score clips whose slug matches the glob
    --clipai-only              Skip AutoFlip load (useful before cache
                               regeneration)
    --dry-run                  Enumerate clips + skip the ClipAI pipeline
                               call (fast iteration on the scoring layer)

Design notes:

  - The harness NEVER invokes the Docker MediaPipe runner directly.
    That's expensive and environment-dependent; the cached JSON is
    the supported comparison input. A missing cache file is a
    reported "skipped" row, not a failure.

  - The ClipAI pipeline invocation is a seam that can be plugged in
    three different ways (inline extractor → segmenter, cached
    extractor → segmenter, or backend HTTP call). This file calls a
    ``run_clipai_on_clip(clip, video_path)`` helper that is a
    placeholder in the current revision: it dry-runs for every
    clip and emits a timeline of one-segment-per-clip so the
    scoring layer has something to chew on. The real implementation
    lives in a follow-up that wires ``measure_autoflip_parity.py``'s
    inline-segmenter path to a real-video input.
"""
from __future__ import annotations

import argparse
import fnmatch
import json
import logging
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Optional

logger = logging.getLogger("compare_autoflip_vs_clipai")


# ─────────────────── Target zones (Part D6) ───────────────────
#
# Fallback bands used when a human ground-truth sidecar is not
# available for a clip. A clip PASSES when its median_hold_sec falls
# inside the target range AND its segments_under_1s_rate is under the
# allowed ceiling. Jalon can tune these after the first real run.

TARGET_ZONES: dict[str, dict[str, float]] = {
    "multi_speaker_panel": {
        "median_hold_min": 3.0,
        "median_hold_max": 6.0,
        "under_1s_max": 0.05,
    },
    "animation": {
        # Action anime: short cuts are the norm
        "median_hold_min": 0.8,
        "median_hold_max": 2.0,
        "under_1s_max": 0.10,
    },
    "animation_dialogue": {
        "median_hold_min": 2.5,
        "median_hold_max": 5.0,
        "under_1s_max": 0.05,
    },
    "sports_basketball": {
        "median_hold_min": 1.5,
        "median_hold_max": 3.5,
        "under_1s_max": 0.10,
    },
    "sports_racing": {
        "median_hold_min": 2.5,
        "median_hold_max": 5.0,
        "under_1s_max": 0.05,
    },
    "sports": {
        "median_hold_min": 2.0,
        "median_hold_max": 4.5,
        "under_1s_max": 0.08,
    },
    # Music video is handled with a subtype split below; these are
    # the defaults when no subtype is pinned.
    "music_video": {
        "median_hold_min": 1.0,
        "median_hold_max": 4.5,
        "under_1s_max": 0.15,
    },
    "music_video_performance": {
        "median_hold_min": 1.0,
        "median_hold_max": 2.5,
        "under_1s_max": 0.15,
    },
    "music_video_narrative": {
        "median_hold_min": 2.5,
        "median_hold_max": 5.0,
        "under_1s_max": 0.05,
    },
}


def target_zone_for(clip: dict) -> Optional[dict[str, float]]:
    """Look up the target zone for a clip, falling back through
    (clipcontenttype + subtype) → clipcontenttype → None."""
    ct = clip.get("target_clipcontenttype") or ""
    sub = clip.get("subtype") or ""
    if ct == "music_video" and sub:
        key = f"music_video_{sub}"
        if key in TARGET_ZONES:
            return TARGET_ZONES[key]
    return TARGET_ZONES.get(ct)


# ─────────────────── Scoring ───────────────────


@dataclass
class ClipResult:
    slug: str
    content_type: str
    target_clipcontenttype: str
    subtype: Optional[str]
    autoflip: Optional[dict[str, Any]] = None
    clipai: Optional[dict[str, Any]] = None
    ground_truth: Optional[dict[str, Any]] = None
    verdicts: dict[str, str] = field(default_factory=dict)
    notes: list[str] = field(default_factory=list)


def _derive_crop_centers_pct(events: list[dict]) -> list[float]:
    """Per-event crop_cx in percent (0-100) for the parity metrics."""
    return [float(e.get("crop_cx", 0.5)) * 100.0 for e in events]


def score_timeline(events: list[dict]) -> dict[str, Any]:
    """Run every applicable parity metric over an AutoFlip-shape
    event list.

    Returns a dict ready to paste into the markdown rollup.
    """
    from backend.services.autoflip_parity_metrics import (
        cut_to_hold_ratio,
        max_acceleration,
        max_jerk,
        overlap_count,
    )

    if not events:
        return {
            "n_segments": 0,
            "note": "empty event list",
        }

    crop_centers = _derive_crop_centers_pct(events)
    hold = cut_to_hold_ratio(events)

    # overlap_count consumes (start, end) spans; derive from the
    # scene_change flag distribution.
    segment_starts = [float(e["t"]) for e in events if e.get("scene_change")]
    if not segment_starts:
        segment_starts = [float(events[0]["t"])]
    segment_ends = segment_starts[1:] + [float(events[-1]["t"])]
    spans = list(zip(segment_starts, segment_ends))

    return {
        "n_segments": hold.get("n_segments", 0),
        "median_hold_sec": hold.get("median_hold_sec"),
        "p25": hold.get("p25"),
        "p75": hold.get("p75"),
        "p95": hold.get("p95"),
        "segments_under_1s_rate": hold.get("segments_under_1s_rate"),
        "segments_over_8s_rate": hold.get("segments_over_8s_rate"),
        "max_acceleration": max_acceleration(crop_centers),
        "max_jerk": max_jerk(crop_centers),
        "overlap_count": overlap_count(spans),
    }


def verdict_for(metrics: dict[str, Any], zone: Optional[dict[str, float]]) -> str:
    """Return PASS / MARGINAL / MISS / UNKNOWN for a (clip, tool) pair."""
    if not metrics or metrics.get("n_segments", 0) == 0:
        return "UNKNOWN"
    if zone is None:
        return "UNKNOWN"
    median = metrics.get("median_hold_sec")
    under = metrics.get("segments_under_1s_rate")
    if median is None or under is None:
        return "UNKNOWN"
    in_median = zone["median_hold_min"] <= median <= zone["median_hold_max"]
    under_ok = under <= zone["under_1s_max"]
    if in_median and under_ok:
        return "PASS"
    if in_median or under_ok:
        return "MARGINAL"
    return "MISS"


# ─────────────────── Pipeline invocation seam ───────────────────


def run_clipai_on_clip(
    clip: dict,
    video_path: Optional[Path],
    *,
    dry_run: bool = False,
) -> Optional[list[dict]]:
    """Produce a ClipAI timeline event list for a clip.

    **Current revision is a stub.** The real implementation will
    crib from ``measure_autoflip_parity.py``'s inline segmenter
    path — build a fake ``FaceRegistry`` + dense ``FrameFaces``
    list from a real extraction cache, call
    ``build_reframe_segments``, and translate with
    ``export_autoflip_compatible.reframe_segments_to_events``.

    For now, the stub emits a one-segment timeline covering
    ``[0, clip.duration_sec]`` so the scoring layer has a
    well-formed input to chew on and produces a coherent markdown
    rollup. When the real invocation lands, this stub becomes
    obsolete and the harness actually measures ClipAI.
    """
    if dry_run or video_path is None:
        duration = float(clip.get("duration_sec") or 10.0)
        fps = 30.0
        events = []
        n = max(1, int(duration * fps))
        for fi in range(n):
            events.append({
                "frame": fi,
                "t": fi / fps,
                "crop_cx": 0.5,
                "crop_cy": 0.5,
                "crop_w": 0.3164,
                "crop_h": 1.0,
                "scene_change": fi == 0,
            })
        return events

    # Real invocation path — TODO in a follow-up session.
    logger.warning(
        "[%s] run_clipai_on_clip: real invocation not yet wired; "
        "returning None so the harness reports 'clipai_skipped'.",
        clip.get("slug"),
    )
    return None


def load_autoflip_timeline(
    clip: dict, autoflip_dir: Path,
) -> Optional[list[dict]]:
    slug = clip["slug"]
    path = autoflip_dir / f"{slug}.json"
    if not path.is_file():
        return None
    try:
        payload = json.loads(path.read_text())
    except (OSError, json.JSONDecodeError) as e:
        logger.warning("[%s] AutoFlip JSON load failed: %s", slug, e)
        return None
    events = payload.get("events") or []
    if not events:
        return None
    return events


def load_ground_truth_timeline(
    clip: dict, ground_truth_dir: Path,
) -> Optional[list[dict]]:
    slug = clip["slug"]
    path = ground_truth_dir / f"{slug}.json"
    if not path.is_file():
        return None
    try:
        payload = json.loads(path.read_text())
    except (OSError, json.JSONDecodeError):
        return None
    return payload.get("events") or None


# ─────────────────── Rollup rendering ───────────────────


_GROUP_ORDER = [
    ("panels", {"multi_speaker_panel"}),
    ("anime", {"animation", "animation_dialogue"}),
    ("sports", {"sports", "sports_basketball", "sports_racing"}),
    ("music", {"music_video"}),
]


def _group_for(clip: dict) -> str:
    ct = clip.get("target_clipcontenttype") or ""
    for group_name, cts in _GROUP_ORDER:
        if ct in cts:
            return group_name
    return "other"


def _fmt(v: Any, digits: int = 2, missing: str = "—") -> str:
    if v is None:
        return missing
    if isinstance(v, (int, float)):
        return f"{v:.{digits}f}"
    return str(v)


def render_markdown(
    results: list[ClipResult],
    *,
    autoflip_outputs_dir: Path,
    clipai_invocation: str,
) -> str:
    """Emit the per-group markdown rollup."""
    by_group: dict[str, list[ClipResult]] = {}
    for r in results:
        by_group.setdefault(
            _group_for({
                "target_clipcontenttype": r.target_clipcontenttype,
                "subtype": r.subtype,
            }),
            [],
        ).append(r)

    out: list[str] = []
    out.append("# Week 3 — Real-content comparison results\n")
    out.append(
        "Generated by "
        "`backend/scripts/compare_autoflip_vs_clipai.py`. Each row is "
        "one (clip, tool) pair. Verdict uses the per-content-type "
        "target zone from `TARGET_ZONES` when no human ground-truth "
        "sidecar is available.\n"
    )
    out.append(
        f"- Clips scored: **{len(results)}**\n"
        f"- AutoFlip outputs dir: `{autoflip_outputs_dir}`\n"
        f"- ClipAI invocation mode: `{clipai_invocation}`\n"
    )

    for group, cts in _GROUP_ORDER:
        group_results = by_group.get(group) or []
        if not group_results:
            continue
        out.append(f"\n## {group.title()}\n")
        out.append(
            "| Clip | Tool | median | p25 | p75 | under_1s | over_8s | "
            "max_accel | max_jerk | verdict |\n"
        )
        out.append(
            "|---|---|---|---|---|---|---|---|---|---|\n"
        )
        for r in group_results:
            for tool, label in (
                ("autoflip", "autoflip"),
                ("clipai", "**clipai**"),
                ("ground_truth", "ground_truth"),
            ):
                m = getattr(r, tool)
                if m is None:
                    out.append(
                        f"| `{r.slug}` | {label} | "
                        f"— | — | — | — | — | — | — | SKIPPED |\n"
                    )
                    continue
                out.append(
                    f"| `{r.slug}` | {label} | "
                    f"{_fmt(m.get('median_hold_sec'))} | "
                    f"{_fmt(m.get('p25'))} | "
                    f"{_fmt(m.get('p75'))} | "
                    f"{_fmt(m.get('segments_under_1s_rate'), 2)} | "
                    f"{_fmt(m.get('segments_over_8s_rate'), 2)} | "
                    f"{_fmt(m.get('max_acceleration'))} | "
                    f"{_fmt(m.get('max_jerk'))} | "
                    f"{r.verdicts.get(tool, 'UNKNOWN')} |\n"
                )
            if r.notes:
                out.append(
                    f"| | _{' · '.join(r.notes)}_ | | | | | | | | |\n"
                )
    return "".join(out)


# ─────────────────── Main loop ───────────────────


def main(argv: Optional[list[str]] = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--manifest", default="tests/real_content/manifest.json",
    )
    parser.add_argument(
        "--autoflip-outputs",
        default="tests/autoflip_reference_outputs",
    )
    parser.add_argument(
        "--ground-truth-dir",
        default="tests/real_content/ground_truth",
    )
    parser.add_argument(
        "--output",
        default="docs/week3_real_content_results.md",
    )
    parser.add_argument(
        "--json-out",
        default="/tmp/week3_results.json",
    )
    parser.add_argument(
        "--filter", default="*",
        help="Only score clips whose slug matches the glob",
    )
    parser.add_argument(
        "--clipai-only", action="store_true",
        help="Skip AutoFlip load (mark every clip's autoflip as SKIPPED)",
    )
    parser.add_argument(
        "--dry-run", action="store_true",
        help="Emit stubbed ClipAI timelines without invoking the pipeline",
    )
    parser.add_argument(
        "--quiet", action="store_true",
    )
    args = parser.parse_args(argv)

    logging.basicConfig(
        level=logging.WARNING if args.quiet else logging.INFO,
        format="%(levelname)s %(name)s: %(message)s",
    )

    manifest_path = Path(args.manifest)
    if not manifest_path.is_file():
        logger.error("manifest not found at %s", manifest_path)
        return 2
    manifest = json.loads(manifest_path.read_text())

    autoflip_dir = Path(args.autoflip_outputs)
    gt_dir = Path(args.ground_truth_dir)

    results: list[ClipResult] = []
    filter_glob = args.filter

    for clip in manifest.get("clips", []):
        slug = clip.get("slug") or ""
        if not fnmatch.fnmatch(slug, filter_glob):
            continue

        result = ClipResult(
            slug=slug,
            content_type=clip.get("content_type") or "",
            target_clipcontenttype=clip.get("target_clipcontenttype") or "",
            subtype=clip.get("subtype"),
        )

        # AutoFlip timeline
        if args.clipai_only:
            result.notes.append("autoflip skipped (--clipai-only)")
        else:
            af_events = load_autoflip_timeline(clip, autoflip_dir)
            if af_events is None:
                result.notes.append(
                    f"no AutoFlip cache at {autoflip_dir}/{slug}.json"
                )
            else:
                result.autoflip = score_timeline(af_events)

        # ClipAI timeline
        ca_events = run_clipai_on_clip(
            clip, video_path=None, dry_run=args.dry_run,
        )
        if ca_events is None:
            result.notes.append("clipai pipeline invocation not wired")
        else:
            result.clipai = score_timeline(ca_events)

        # Optional human ground truth
        gt_events = load_ground_truth_timeline(clip, gt_dir)
        if gt_events:
            result.ground_truth = score_timeline(gt_events)

        # Verdicts
        zone = target_zone_for(clip)
        for tool in ("autoflip", "clipai", "ground_truth"):
            m = getattr(result, tool)
            if m is None:
                continue
            result.verdicts[tool] = verdict_for(m, zone)

        results.append(result)

    # Emit markdown
    md_body = render_markdown(
        results,
        autoflip_outputs_dir=autoflip_dir,
        clipai_invocation=(
            "stub (dry_run=%s)" % args.dry_run
            if args.dry_run else "real (not yet wired)"
        ),
    )
    Path(args.output).parent.mkdir(parents=True, exist_ok=True)
    Path(args.output).write_text(md_body)
    logger.info("wrote markdown rollup to %s", args.output)

    # Emit JSON dump
    payload = {
        "schema": "week3_real_content_results/1",
        "manifest_path": str(manifest_path),
        "autoflip_outputs_dir": str(autoflip_dir),
        "filter": args.filter,
        "results": [
            {
                "slug": r.slug,
                "content_type": r.content_type,
                "target_clipcontenttype": r.target_clipcontenttype,
                "subtype": r.subtype,
                "autoflip": r.autoflip,
                "clipai": r.clipai,
                "ground_truth": r.ground_truth,
                "verdicts": r.verdicts,
                "notes": r.notes,
            }
            for r in results
        ],
    }
    Path(args.json_out).parent.mkdir(parents=True, exist_ok=True)
    Path(args.json_out).write_text(json.dumps(payload, indent=2))
    logger.info("wrote JSON dump to %s", args.json_out)

    return 0


if __name__ == "__main__":
    sys.exit(main())
